rm(list=ls())
IBM <-read.csv("IBMStock.csv", header = T)
GE <-read.csv("GEStock.csv", header = T)
Boeing <-read.csv("BoeingStock.csv", header = T)
CocaCola <-read.csv("CocaColaStock.csv", header = T)
ProcterGamble <-read.csv("ProcterGambleStock.csv", header = T)
str(GE)
IBM$Date = as.Date(IBM$Date, "%m/%d/%y")
GE$Date = as.Date(GE$Date, "%m/%d/%y")
CocaCola$Date = as.Date(CocaCola$Date, "%m/%d/%y")
ProcterGamble$Date = as.Date(ProcterGamble$Date, "%m/%d/%y")
Boeing$Date = as.Date(Boeing$Date, "%m/%d/%y")
plot(GE, type = "l", main = "GE")
plot(IBM, type = "l", main = "IBM")
plot(Boeing, type = "l", main = "Boeing")
plot(CocaCola, type = "l", main = "CocaCola")
plot(ProcterGamble, type = "l", main = "Procter & Gamble")
GE
summary(IBM$StockPrice)
summary(GE$StockPrice)
summary(CocaCola$StockPrice)
summary(Boeing$StockPrice)
sd(ProcterGamble$StockPrice)
sd(IBM$StockPrice)
sd(GE$StockPrice)
sd(CocaCola$StockPrice)
sd(Boeing$StockPrice)
plot(CocaCola, type = "l", main = "CocaCola")
which.max(CocaCola$StockPrice)
CocaCola[37,]
lines(ProcterGamble$Date, ProcterGamble$StockPrice, col = "Red")
abline(v=as.Date(c("2000-03-01")), lwd=2)
plot(CocaCola, type = "l", main = "CocaCola")
lines(ProcterGamble$Date, ProcterGamble$StockPrice, col = "Red")
abline(v=as.Date(c("1983-03-01")), lwd=2)
summary(ProcterGamble$StockPrice)
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], col="blue")
lines(IBM$Date[301:432], IBM$StockPrice[301:432], col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432], col="purple")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], col="black")
abline(v=as.Date(c("2000-03-01")), lwd=1)

plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], col="blue")
lines(IBM$Date[301:432], IBM$StockPrice[301:432], col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432], col="purple")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], col="black")
abline(v=as.Date(c("1997-09-01")), lwd=1)
abline(v=as.Date(c("1997-11-01")), lwd=1)

plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], col="blue")
lines(IBM$Date[301:432], IBM$StockPrice[301:432], col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432], col="purple")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], col="black")
abline(v=as.Date(c("2004-01-01")), lwd=1)
abline(v=as.Date(c("2005-01-01")), lwd=1)
tapply(IBM$StockPrice, months(IBM$Date), mean)
summary(tapply(IBM$StockPrice, months(IBM$Date), mean))
sort(tapply(IBM$StockPrice, months(IBM$Date), mean))
summary(IBM$StockPrice)
sort(tapply(GE$StockPrice, months(GE$Date), mean))
sort(tapply(CocaCola$StockPrice, months(CocaCola$Date), mean))
