rm(list=ls())
cps <-read.csv("CPSData.csv", header = T)
str(cps)
summary(cps)
sort(table(cps$State))
(116639 +7073) / (116639 +7073 + 7590)
sort(table(cps$Race[cps$Hispanic == 1]))
# sum(is.na(cps$Age)) # 0
# table(is.na(cps))
table(is.na(cps[,4]))
table(is.na(cps[,6]))
table(is.na(cps[,8]))
table(is.na(cps[,13]))
table(is.na(cps[,14]))
table(cps$Region, is.na(cps$Married))
table(cps$Sex, is.na(cps$Married))
table(cps$Age, is.na(cps$Married))
table(cps$Citizenship, is.na(cps$Married))
table(cps$State, is.na(cps$MetroAreaCode))
table(cps$Region, is.na(cps$MetroAreaCode))
table(cps$State, is.na(cps$MetroAreaCode))
tapply(is.na(cps$MetroAreaCode),cps$State, mean)
sort(tapply(is.na(cps$MetroAreaCode),cps$State, mean))
MetroAreaMap  <-read.csv("MetroAreaCodes.csv", header = T)
CountryMap <- read.csv("CountryCodes.csv", header = T)
cps = merge(cps, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
sum(is.na(cps$MetroAreaCode))
sort(table(cps$MetroArea))
sort(tapply(cps$Hispanic,cps$MetroArea,mean))
# sort(table(cps$MetroArea[cps$Race == "Asian"]))
# mean(table(cps$MetroArea[cps$Race == "Asian"]))
sort(tapply(cps$Race=="Asian", cps$MetroArea, mean))
sort(tapply(cps$Education == "No high school diploma", cps$MetroArea, mean, na.rm = TRUE))
cps = merge(cps, CountryMap, by.x="CountryOfBirthCode", by.y ="Code", all.x=TRUE)
sum(is.na(cps$Country))
table(cps$Country)
sort(table(cps$Country))
tapply(cps$Country !="United States", cps$MetroArea =="New York-Northern New Jersey-Long Island, NY-NJ-PA",mean, na.rm=TRUE )
tapply(cps$Country !="United States", cps$MetroArea =="New York-Northern New Jersey-Long Island, NY-NJ-PA",mean, na.rm=TRUE )
sort(tapply(cps$Country =="India", cps$MetroArea ,max, na.rm=TRUE ))
tapply(cps$MetroArea ,cps$Country =="India", sum, na.rm=TRUE )
sort(tapply(cps$Country =="India", cps$MetroArea, sum, na.rm = T))
sort(tapply(cps$Country =="Brazil", cps$MetroArea, sum, na.rm = T))
sort(tapply(cps$Country =="Somalia", cps$MetroArea, sum, na.rm = T))
sort(tapply(cps$Country =="Nigeria", cps$MetroArea, sum, na.rm = T))
sort(tapply(cps$Country =="Jamaica", cps$MetroArea, sum, na.rm = T))

