rm(list=ls())
mvt <-read.csv("mvtWeek1.csv", header = T)
str(mvt)
max(mvt$ID)
min(mvt$Beat)
sum(mvt$Arrest == T)
sum(mvt$LocationDescription == "ALLEY")
head(mvt$Date)
tail(mvt$Date)
DateConvert = as.Date(strptime(mvt$Date, "%m/%d/%y %H:%M"))
head(DateConvert)
tail(DateConvert)
summary(DateConvert)
mvt$Month = months(DateConvert)
mvt$Weekday = weekdays(DateConvert)
table(mvt$Month)
table(mvt$Weekday)
table(mvt$Month[mvt$Arrest==T])
mvt$Date = DateConvert
hist(mvt$Date, breaks=100)
summary(mvt$Date)
boxplot(mvt$Date[mvt$Arrest==T])
boxplot(mvt$Date[mvt$Arrest==F])
boxplot(mvt$Date~mvt$Arrest)
myr1 <- subset(mvt,mvt$Date >= "2001-1-01" & mvt$Date <= "2001-12-31")
table(mvt$Arrest, mvt$Year)
myr <-subset(mvt,mvt$Date >="2007-01-01" & mvt$Date <="2007-12-31")
table(mvt$Month,mvt$Arrest==T)
table(myr$Month,myr$Arrest==T)
mean(myr$Arrest==T)
mean(myr1$Arrest==T)
sort(table(mvt$LocationDescription))
top5 <- subset(mvt, mvt$LocationDescription =="STREET" | mvt$LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)" | mvt$LocationDescription =="ALLEY"
               | mvt$LocationDescription == "GAS STATION" | mvt$LocationDescription =="DRIVEWAY - RESIDENTIAL")
top5$LocationDescription = factor(top5$LocationDescription)
table(top5$LocationDescription,top5$Arrest==T)
a = 249/(249+2059)
d = 132/(132+1543)
g = 439 / (439 +1672)
p = 1603 /(1603 + 13249)
s = 11595/ (144969 + 11595)
str(mvt)
table(mvt$Weekday[mvt$LocationDescription == "GAS STATION"])
sort(table(mvt$Weekday[mvt$LocationDescription == "GAS STATION"]))
sort(table(mvt$Weekday[mvt$LocationDescription == "DRIVEWAY - RESIDENTIAL"]))
